### ISSUE TITLE
Taking inspiration from Home Assistant configuration syntax

### ISSUE THREAD

**Issue by teun95** [adxsoft/logseqadvancedquerybuilder#2]
I haven't yet had the opportunity to use this tool extensively (although it has helped me already), but when I came across it the `not` operator syntax seemed a bit confusing as the _conditions_ share their space with the variables. Perhaps the [Home Assistant (shorthand) notation for some conditions](https://www.home-assistant.io/docs/scripts/conditions/#not-condition) could serve as an inspiration?

Take the following as an example:

```
- blocktags
    - tag1
    - not tag2
    - tag3
    - not tag4
 ```

Loosely based on the Home Assistant condition syntax this would become:

```
- condition:
    and:
      - condition: tag
        tag: tag1
      - condition: tag
        tag: tag3
- condition:
    not:
      - condition: tag
        tag: tag2
      - condition: tag
        tag: tag4

```

The Home Assistant documentation describes OR and AND operators as well. It's not perfect and it takes a bit more space, but it feels like it's a bit more logical and future proof.
